---
- name: Install php and deps
  yum:
    name: "php{{ php_version }}, php{{ php_version }}-ctype, php{{ php_version }}-curl, php{{ php_version }}-dom, php{{ php_version }}-gd, php{{ php_version }}-intl, php{{ php_version }}-mbstring, php{{ php_version }}-simplexml, php{{ php_version }}-soap, php{{ php_version }}-xsl, php{{ php_version }}-json, php{{ php_version }}-iconv, php{{ php_version }}-bcmath, php{{ php_version }}-redis, php{{ php_version }}-ctype, php{{ php_version }}-curl, php{{ php_version }}-dom, php{{ php_version }}-gd, php{{ php_version }}-intl, php{{ php_version }}-mbstring, php{{ php_version }}-simplexml, php{{ php_version }}-soap, php{{ php_version }}-xsl, php{{ php_version }}-json, php{{ php_version }}-iconv, php{{ php_version }}-bcmath, php{{ php_version }}-xsl, php{{ php_version }}-zip, vim, git"
    state: present

- name: Increase Memory Limit
  lineinfile:
    path: /etc/php/{{ php_version }}/apache2/php.ini
    regexp: 'memory_limit = 128M'
    line: 'memory_limit = 2048M'

- name: Increase Execution Time
  lineinfile:
    path: /etc/php/{{ php_version }}/apache2/php.ini
    regexp: 'max_execution_time = 30'
    line: 'max_execution_time = 1800'

- name: Increase Upload Filesize
  lineinfile:
    path: /etc/php/{{ php_version }}/apache2/php.ini
    regexp: 'upload_max_filesize = 2M'
    line: 'upload_max_filesize = 16M'

- name: Increase Post Size
  lineinfile:
    path: /etc/php/{{ php_version }}/apache2/php.ini
    regexp: 'post_max_size = 8M'
    line: 'post_max_size = 32M'

- name: Increase Memory Limit
  lineinfile:
    path: /etc/php/{{ php_version }}/apache2/php.ini
    regexp: 'memory_limit = 128M'
    line: 'memory_limit = 256M'

- name: Enable Display Errors
  lineinfile:
    path: /etc/php/{{ php_version }}/apache2/php.ini
    regexp: 'display_errors = Off'
    line: 'display_errors = On'
  notify:
    - Restart Apache2